spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORDS}
    driver-class-name: org.postgresql.Driver

  application:
    name: bron-business


  # JWT Configuratio


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCE_SERVER_ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
      serialization:
        write-dates-as-timestamps: false

logging:
  file:
    name: bronapplogfile.log
  level:
    az.bron.business: WARN


server:
  port: ${SERVER_PORT}
debug: on
jwt:
  auth:
    converter:
      principal-attribute: principal_username
      resource-id: bron_client

aws:
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}