spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bron_business
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  application:
    name: bron-business

  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
      serialization:
        write-dates-as-timestamps: false



server:
  port: 8088
debug: on