spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORDS}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: prod

  application:
    name: bron-business

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:

      hibernate:
        search:
          enabled: true
          backend:
            directory:
              root: ./indexes
              type: local-filesystem
          default:
            type: lucene
          analysis:
            configurer: class:az.bron.config.AnalysisConfigurer
        format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
      serialization:
        write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_SMTP_USERNAME}
    password: ${GMAIL_SMTP_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

logging:
  file:
    name: bronapplogfile.log
  level:
    az.bron.business: WARN

server:
  port: ${SERVER_PORT}
debug: on

aws:
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}
  bucket:
    name: ${AWS_S3_BUCKET_NAME}
    url: ${AWS_S3_BUCKET_URL}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400

APP_URL: ${APP_URL}
