spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bron_business
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  application:
    name: bron-business

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: mock-google-client-id
            client-secret: mock-google-client-secret
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        search:
          strategy: drop-and-create-and-drop
          enabled: true
          backend:
            directory:
              root: ./indexes
              type: local-filesystem
          default:
            type: lucene
          analysis:
            configurer: class:az.bron.config.AnalysisConfigurer
        format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

    jackson:
      serialization:
        write-dates-as-timestamps: false

  mail:
    host: smtp.example.com
    port: 587
    username: mock-email@example.com
    password: mockpassword
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.example.com

logging:
  file:
    name: bronapplogfile.log
  level:
    az.bron.business: WARN

server:
  port: 8088

debug: on

aws:
  access:
    key: mock-access-key
  secret:
    key: mock-secret-key
  bucket:
    name: mock-bucket
    url: http://localhost:4566/mock-s3

security:
  jwt:
    secret-key: secret-key
    expiration-time: 36000000

APP_URL: http://localhost:8080
